# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeptResponsibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('desg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('pi', models.CharField(max_length=200)),
                ('co_pi', models.CharField(max_length=200)),
                ('funding_agency', models.CharField(max_length=200)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Completed'), ('0', 'ongoing')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('published', models.CharField(choices=[('conference', 'Conference'), ('journal', 'Journal')], max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Recognitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_interests', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('1', 'Completed'), ('0', 'Continuing')], max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('thesis_title', models.CharField(max_length=200)),
                ('supervisors', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('designation', models.CharField(choices=[('professor', 'Professor'), ('assistant professor', 'Assistant Professor'), ('associate professor', 'Associate Professor')], max_length=50)),
                ('office_room_num', models.CharField(max_length=20)),
                ('office_phone_ext', models.IntegerField()),
                ('webmail', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('residence', models.CharField(max_length=500)),
                ('residence_phone_num', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=200)),
                ('start_month', models.CharField(choices=[('dec', 'December'), ('nov', 'November'), ('aug', 'August'), ('mar', 'March'), ('feb', 'February'), ('oct', 'October'), ('sep', 'September'), ('jun', 'June'), ('apr', 'April'), ('jan', 'January'), ('may', 'May'), ('jul', 'July')], max_length=50)),
                ('end_month', models.CharField(choices=[('dec', 'December'), ('nov', 'November'), ('aug', 'August'), ('mar', 'March'), ('feb', 'February'), ('oct', 'October'), ('sep', 'September'), ('jun', 'June'), ('apr', 'April'), ('jan', 'January'), ('may', 'May'), ('jul', 'July')], max_length=50)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_main.User')),
            ],
        ),
        migrations.AddField(
            model_name='teaching',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_main.User'),
        ),
        migrations.AddField(
            model_name='students',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_main.User'),
        ),
        migrations.AddField(
            model_name='researchinterests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_main.User'),
        ),
        migrations.AddField(
            model_name='recognitions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_main.User'),
        ),
        migrations.AddField(
            model_name='publication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_main.User'),
        ),
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_main.User'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_main.User'),
        ),
        migrations.AddField(
            model_name='deptresponsibilities',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_main.User'),
        ),
    ]
