# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('0', 'ongoing'), ('1', 'Completed')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('0', 'Continuing'), ('1', 'Completed')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('associate professor', 'Associate Professor'), ('assistant professor', 'Assistant Professor'), ('professor', 'Professor')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='office_phone_ext',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='office_room_num',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='residence',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='residence_phone_num',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='webmail',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_month',
            field=models.CharField(choices=[('jan', 'January'), ('aug', 'August'), ('dec', 'December'), ('sep', 'September'), ('mar', 'March'), ('nov', 'November'), ('oct', 'October'), ('jul', 'July'), ('apr', 'April'), ('jun', 'June'), ('feb', 'February'), ('may', 'May')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_month',
            field=models.CharField(choices=[('jan', 'January'), ('aug', 'August'), ('dec', 'December'), ('sep', 'September'), ('mar', 'March'), ('nov', 'November'), ('oct', 'October'), ('jul', 'July'), ('apr', 'April'), ('jun', 'June'), ('feb', 'February'), ('may', 'May')], max_length=50),
        ),
    ]
