# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0003_auto_20171110_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='published',
            field=models.CharField(choices=[('journal', 'Journal'), ('conference', 'Conference')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('1', 'Completed'), ('0', 'Continuing')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('professor', 'Professor'), ('associate professor', 'Associate Professor'), ('assistant professor', 'Assistant Professor')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_month',
            field=models.CharField(choices=[('jun', 'June'), ('feb', 'February'), ('may', 'May'), ('sep', 'September'), ('nov', 'November'), ('aug', 'August'), ('dec', 'December'), ('mar', 'March'), ('jul', 'July'), ('jan', 'January'), ('oct', 'October'), ('apr', 'April')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_month',
            field=models.CharField(choices=[('jun', 'June'), ('feb', 'February'), ('may', 'May'), ('sep', 'September'), ('nov', 'November'), ('aug', 'August'), ('dec', 'December'), ('mar', 'March'), ('jul', 'July'), ('jan', 'January'), ('oct', 'October'), ('apr', 'April')], max_length=50),
        ),
    ]
