# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0004_auto_20171110_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='course',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('ongoing', '0'), ('Completed', '1')], max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='published',
            field=models.CharField(choices=[('Journal', 'journal'), ('Conference', 'conference')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('Continuing', '0'), ('Completed', '1')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Assistant Professor', 'Assistant Professor')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_month',
            field=models.CharField(choices=[('January', 'jan'), ('November', 'nov'), ('July', 'jul'), ('April', 'apr'), ('February', 'feb'), ('October', 'oct'), ('June', 'jun'), ('August', 'aug'), ('December', 'dec'), ('May', 'may'), ('March', 'mar'), ('September', 'sep')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_month',
            field=models.CharField(choices=[('January', 'jan'), ('November', 'nov'), ('July', 'jul'), ('April', 'apr'), ('February', 'feb'), ('October', 'oct'), ('June', 'jun'), ('August', 'aug'), ('December', 'dec'), ('May', 'may'), ('March', 'mar'), ('September', 'sep')], max_length=50),
        ),
    ]
