# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0010_auto_20171111_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('Completed', '1'), ('ongoing', '0')], max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='published',
            field=models.CharField(choices=[('Conference', 'conference'), ('Journal', 'journal')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor')], default='', max_length=50),
        ),
    ]
