# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0012_auto_20171111_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('Continuing', '0'), ('Completed', '1')], max_length=200),
        ),
    ]
