# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0015_auto_20171111_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='static/faculty_img/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('Completed', '1'), ('ongoing', '0')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Assistant Professor', 'Assistant Professor')], default='', max_length=50),
        ),
    ]
