# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0016_auto_20171111_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(upload_to='static/faculty_img/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='published',
            field=models.CharField(choices=[('Journal', 'journal'), ('Conference', 'conference')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('Completed', '1'), ('Continuing', '0')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], default='', max_length=50),
        ),
    ]
