# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0018_auto_20171111_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='static/portal/assets/img/find_user.pngs', upload_to='static/faculty_img/'),
        ),
    ]
