# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0020_auto_20171111_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='find_user.png', upload_to='static/faculty_img'),
        ),
    ]
