# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0021_auto_20171113_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching',
            name='semester',
            field=models.CharField(choices=[('Even Semester', 'Even Semester'), ('Odd Semester', 'Odd Semester')], default='Odd Semester', max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('ongoing', '0'), ('Completed', '1')], max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='published',
            field=models.CharField(choices=[('Conference', 'conference'), ('Journal', 'journal')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('Continuing', '0'), ('Completed', '1')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Assistant Professor', 'Assistant Professor')], default='', max_length=50),
        ),
    ]
