# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0022_auto_20171113_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaching',
            old_name='year',
            new_name='session',
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('Completed', '1'), ('ongoing', '0')], max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='published',
            field=models.CharField(choices=[('Journal', 'journal'), ('Conference', 'conference')], max_length=200),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='semester',
            field=models.CharField(choices=[('Odd Semester', 'Odd Semester'), ('Even Semester', 'Even Semester')], default='Odd Semester', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor')], default='', max_length=50),
        ),
    ]
