# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0025_auto_20171114_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='end_date',
            new_name='published_date',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='published',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('ongoing', '0'), ('Completed', '1')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('Ph.D.', 'Ph.D.'), ('M.Tech', 'M.Tech')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Continuing', 'Continuing')], max_length=200),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='semester',
            field=models.CharField(choices=[('Even Semester', 'Even Semester'), ('Odd Semester', 'Odd Semester')], default='Odd Semester', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], default='', max_length=50),
        ),
    ]
