# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0028_auto_20171114_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='published_date',
        ),
        migrations.AddField(
            model_name='publication',
            name='published_year',
            field=models.IntegerField(default=2017),
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('Ph.D.', 'Ph.D.'), ('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('Continuing', 'Continuing'), ('Completed', 'Completed')], max_length=200),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='semester',
            field=models.CharField(choices=[('Even Semester', 'Even Semester'), ('Odd Semester', 'Odd Semester')], default='Odd Semester', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], default='', max_length=50),
        ),
    ]
