# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0040_auto_20171115_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='webpage_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('Ph.D.', 'Ph.D.'), ('M.Tech', 'M.Tech')], max_length=200),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='semester',
            field=models.CharField(choices=[('Odd Semester', 'Odd Semester'), ('Even Semester', 'Even Semester')], default='Odd Semester', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor')], default='', max_length=50),
        ),
    ]
