# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0045_auto_20171118_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Continuing', 'Continuing')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Bio-Tech', 'Bio-Tech'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Chemistry', 'Chemistry'), ('Chemical Engineering', 'Chemical Engineering'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Mathematics', 'Mathematics'), ('Humanities', 'Humanities'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Design', 'Design')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Head of Department', 'Head of Department'), ('Professor', 'Professor')], default='', max_length=50),
        ),
    ]
