# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0046_auto_20171118_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('Ph.D.', 'Ph.D.'), ('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('Continuing', 'Continuing'), ('Completed', 'Completed')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Design', 'Design'), ('Physics', 'Physics'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Bio-Tech', 'Bio-Tech'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Humanities', 'Humanities'), ('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Head of Department', 'Head of Department')], default='', max_length=50),
        ),
    ]
