# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0047_auto_20171118_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='DepartmentN',
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('ongoing', '0'), ('Completed', '1')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('M.Tech', 'M.Tech'), ('B.Tech', 'B.Tech'), ('Ph.D.', 'Ph.D.')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Continuing', 'Continuing')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Bio-Tech', 'Bio-Tech'), ('Design', 'Design'), ('Civil Engineering', 'Civil Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Chemical Engineering', 'Chemical Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Humanities', 'Humanities'), ('Mathematics', 'Mathematics')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Head of Department', 'Head of Department'), ('Professor', 'Professor'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor')], default='', max_length=50),
        ),
    ]
