# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0048_auto_20171118_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('Ph.D.', 'Ph.D.')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('Continuing', 'Continuing'), ('Completed', 'Completed')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Bio-Tech', 'Bio-Tech'), ('Humanities', 'Humanities'), ('Design', 'Design'), ('Physics', 'Physics'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mathematics', 'Mathematics'), ('Civil Engineering', 'Civil Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Chemistry', 'Chemistry'), ('Mechanical Engineering', 'Mechanical Engineering')], default='', max_length=200),
        ),
    ]
