# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0049_auto_20171118_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_code', models.CharField(max_length=200)),
                ('session', models.CharField(max_length=200)),
                ('semester', models.CharField(choices=[('Even Semester', 'Even Semester'), ('Odd Semester', 'Odd Semester')], default='Odd Semester', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('Completed', '1'), ('ongoing', '0')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('Ph.D.', 'Ph.D.'), ('M.Tech', 'M.Tech')], max_length=200),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='semester',
            field=models.CharField(choices=[('Even Semester', 'Even Semester'), ('Odd Semester', 'Odd Semester')], default='Odd Semester', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Design', 'Design'), ('Chemistry', 'Chemistry'), ('Bio-Tech', 'Bio-Tech'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Physics', 'Physics'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Mathematics', 'Mathematics'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Humanities', 'Humanities')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Assistant Professor', 'Assistant Professor'), ('Head of Department', 'Head of Department'), ('Associate Professor', 'Associate Professor')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teachingn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_main.User'),
        ),
    ]
