# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0051_auto_20171118_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Bio-Tech', 'Bio-Tech'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Physics', 'Physics'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Humanities', 'Humanities'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Design', 'Design')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('Ph.D.', 'Ph.D.')], max_length=200),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='semester',
            field=models.CharField(choices=[('Even Semester', 'Even Semester'), ('Odd Semester', 'Odd Semester')], default='Odd Semester', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Bio-Tech', 'Bio-Tech'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Physics', 'Physics'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Humanities', 'Humanities'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Design', 'Design')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Head of Department', 'Head of Department'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='static/faculty_img/find_user.png', upload_to='static/faculty_img'),
        ),
    ]
