# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0053_auto_20171118_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Physics', 'Physics'), ('Humanities', 'Humanities'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mathematics', 'Mathematics'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Bio-Tech', 'Bio-Tech'), ('Chemical Engineering', 'Chemical Engineering')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='thesis_title',
            field=models.CharField(default='   ', max_length=200),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='semester',
            field=models.CharField(choices=[('Odd Semester', 'Odd Semester'), ('Even Semester', 'Even Semester')], default='Odd Semester', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Physics', 'Physics'), ('Humanities', 'Humanities'), ('Chemistry', 'Chemistry'), ('Design', 'Design'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mathematics', 'Mathematics'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Bio-Tech', 'Bio-Tech'), ('Chemical Engineering', 'Chemical Engineering')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Head of Department', 'Head of Department'), ('Professor', 'Professor'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor')], default='', max_length=50),
        ),
    ]
