# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0054_auto_20171128_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mail_verified',
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Design', 'Design'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Mathematics', 'Mathematics'), ('Chemical Engineering', 'Chemical Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Humanities', 'Humanities'), ('Bio-Tech', 'Bio-Tech')], max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('ongoing', '0'), ('Completed', '1')], max_length=200),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='semester',
            field=models.CharField(choices=[('Even Semester', 'Even Semester'), ('Odd Semester', 'Odd Semester')], default='Odd Semester', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Design', 'Design'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Mathematics', 'Mathematics'), ('Chemical Engineering', 'Chemical Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Humanities', 'Humanities'), ('Bio-Tech', 'Bio-Tech')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Head of Department', 'Head of Department'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], default='', max_length=50),
        ),
    ]
