# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0055_auto_20171128_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Humanities', 'Humanities'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mathematics', 'Mathematics'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Design', 'Design'), ('Bio-Tech', 'Bio-Tech'), ('Mechanical Engineering', 'Mechanical Engineering')], max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='end_year',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_year',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('Ph.D.', 'Ph.D.'), ('M.Tech', 'M.Tech')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Continuing', 'Continuing')], max_length=200),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='semester',
            field=models.CharField(choices=[('Odd Semester', 'Odd Semester'), ('Even Semester', 'Even Semester')], default='Odd Semester', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Humanities', 'Humanities'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mathematics', 'Mathematics'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Design', 'Design'), ('Bio-Tech', 'Bio-Tech'), ('Mechanical Engineering', 'Mechanical Engineering')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Head of Department', 'Head of Department')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_main.User'),
        ),
    ]
