# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0058_auto_20171129_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='type',
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Design', 'Design'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Humanities', 'Humanities'), ('Bio-Tech', 'Bio-Tech'), ('Civil Engineering', 'Civil Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Chemical Engineering', 'Chemical Engineering')], max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('Completed', '1'), ('ongoing', '0')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('M.Tech', 'M.Tech'), ('B.Tech', 'B.Tech'), ('Ph.D.', 'Ph.D.')], max_length=200),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='semester',
            field=models.CharField(choices=[('Even Semester', 'Even Semester'), ('Odd Semester', 'Odd Semester')], default='Odd Semester', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Design', 'Design'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Humanities', 'Humanities'), ('Bio-Tech', 'Bio-Tech'), ('Civil Engineering', 'Civil Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Chemical Engineering', 'Chemical Engineering')], default='', max_length=200),
        ),
    ]
