# Generated by Django 2.0 on 2017-12-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0060_auto_20171218_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Bio-Tech', 'Bio-Tech'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Physics', 'Physics'), ('Humanities', 'Humanities'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Design', 'Design')], max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('ongoing', '0'), ('Completed', '1')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('M.Tech', 'M.Tech'), ('B.Tech', 'B.Tech'), ('Ph.D.', 'Ph.D.')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Continuing', 'Continuing')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Bio-Tech', 'Bio-Tech'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Physics', 'Physics'), ('Humanities', 'Humanities'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Design', 'Design')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Head of Department', 'Head of Department')], default='', max_length=50),
        ),
    ]
