# Generated by Django 2.0.5 on 2018-06-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_main', '0062_auto_20180623_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('Bio-Tech', 'Bio-Tech'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Chemistry', 'Chemistry'), ('Chemical Engineering', 'Chemical Engineering'), ('Humanities', 'Humanities'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Physics', 'Physics'), ('Design', 'Design'), ('Civil Engineering', 'Civil Engineering'), ('Mathematics', 'Mathematics')], max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('ongoing', '0'), ('Completed', '1')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.CharField(choices=[('Ph.D.', 'Ph.D.'), ('M.Tech', 'M.Tech'), ('B.Tech', 'B.Tech')], max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Continuing', 'Continuing')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Bio-Tech', 'Bio-Tech'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Chemistry', 'Chemistry'), ('Chemical Engineering', 'Chemical Engineering'), ('Humanities', 'Humanities'), ('Electronics and Electrical Engineering', 'Electronics and Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Physics', 'Physics'), ('Design', 'Design'), ('Civil Engineering', 'Civil Engineering'), ('Mathematics', 'Mathematics')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Associate Professor', 'Associate Professor'), ('Head of Department', 'Head of Department'), ('Assistant Professor', 'Assistant Professor'), ('Professor', 'Professor')], default='', max_length=50),
        ),
    ]
